#############################################################################
# Makefile for building: class-manager
# Generated by qmake (3.1) (Qt 6.5.1)
# Project:  ..\class-manager\class-manager.pro
# Template: app
# Command: E:\QT\qt1\6.5.1\msvc2019_64\bin\qmake.exe -o Makefile ..\class-manager\class-manager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:\QT\qt1\6.5.1\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = E:\QT\qt1\6.5.1\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = E:\QT\qt1\6.5.1\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ..\class-manager\class-manager.pro E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\spec_pre.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\windows-desktop.conf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\qconfig.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt_functions.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt_config.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\spec_post.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\msvc-version.conf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\toolchain.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\default_pre.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resolve_config.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\default_post.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qtquickcompiler.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\entrypoint.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\precompile_header.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\warn_on.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resources_functions.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resources.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\moc.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\opengl.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\uic.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qmake_use.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\file_copies.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\windows.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\testcase_targets.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exceptions.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\yacc.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\lex.prf \
		..\class-manager\class-manager.pro \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Widgets.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Gui.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Core.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6EntryPoint.prl \
		.qmake.stash \
		E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\build_pass.prf \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Widgetsd.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Guid.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Cored.prl \
		E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6EntryPointd.prl
	$(QMAKE) -o Makefile ..\class-manager\class-manager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\spec_pre.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\windows-desktop.conf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\windows-vulkan.conf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\msvc-desktop.conf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\qconfig.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt_functions.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt_config.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\spec_post.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exclusive_builds.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\common\msvc-version.conf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\toolchain.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\default_pre.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\default_pre.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resolve_config.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\default_post.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qtquickcompiler.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\entrypoint.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\precompile_header.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\warn_on.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qt.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resources_functions.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\resources.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\moc.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\opengl.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\uic.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\qmake_use.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\file_copies.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\win32\windows.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\testcase_targets.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\exceptions.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\yacc.prf:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\lex.prf:
..\class-manager\class-manager.pro:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Widgets.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Gui.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Core.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6EntryPoint.prl:
.qmake.stash:
E:\QT\qt1\6.5.1\msvc2019_64\mkspecs\features\build_pass.prf:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Widgetsd.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Guid.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6Cored.prl:
E:\QT\qt1\6.5.1\msvc2019_64\lib\Qt6EntryPointd.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ..\class-manager\class-manager.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
