name: ls
on: 
  # push代码时触发workflow
  push:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  # pull_request时触发workflow
  pull_request:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build-on-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.4.1
        with:
          boost_version: '1.80.0'
          platform_version: 22.04
          toolset: 'gcc'

      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
          target: 'desktop'
      - name: build demo
        run: |
          qmake
          make
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: cp
        run: |
          ls
      - name: pack
        run: |
          mkdir app
          cp class-manager app
          cd app
          linuxdeployqt class-manager
          ls
